docs/_sass/minima/_base.scss
=> Update site header for Jekyll

src/main/java/seedu/address/ui/body/address/PersonDetailPanel.java, src/main/java/seedu/address/ui/body/address/PersonListPanel.java
=> Fix bug where index is always 0

src/main/java/seedu/address/ui/body/address/PersonDetailCard.java, src/main/java/seedu/address/ui/body/address/PersonDetailPanel.java, src/main/java/seedu/address/ui/body/address/PersonModulesCard.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/body/address/PersonListCard.fxml, src/main/resources/view/body/address/PersonModulesCard.fxml
* Also adds a dedicated `PersonModulesCard` to display modules
* Closes #47
=> Hide detail boxes with no data

src/main/java/seedu/address/ui/ResultDisplay.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/MainWindow.fxml, src/main/resources/view/ResultDisplay.fxml
* Add label text styling system
* Add text wrapping
* Fix corners
* Closes #54
=> Change ResultDisplay styling

docs/_config.yml, docs/index.md
=> Update docs to align with this project

src/main/resources/view/CommandBox.fxml, src/main/resources/view/DarkTheme.css
* Adds padding
* Adds rounded corners
* Changes colours
* Closes #60 
Before:
After:
=> Change menu bar styling

README.md
* Add acknowledgement for AB-3
* Closes #16
=> Update miscellaneous docs for v1.1

docs/AboutUs.md, docs/DeveloperGuide.md
I can add more target users in future iterations, but I think this should cover for v1.1.
Edit by @hansstanley:
Closes #24
=> Updates to profile picture and DeveloperGuide.md product scope

src/main/java/seedu/address/logic/commands/AddEventCommand.java, src/main/java/seedu/address/logic/parser/AddEventCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/event/Event.java, src/main/java/seedu/address/model/event/OneTimeEvent.java, src/main/java/seedu/address/model/event/RecurringEvent.java, src/main/java/seedu/address/model/event/UniqueEventList.java, src/main/java/seedu/address/model/event/enums/Interval.java, src/main/java/seedu/address/model/event/exceptions/DuplicateEventException.java, src/main/java/seedu/address/model/event/exceptions/EventNotFoundException.java, src/main/java/seedu/address/model/event/fields/DateTime.java, src/main/java/seedu/address/model/event/fields/Description.java, src/main/java/seedu/address/model/event/fields/Recurrence.java
Added Event Class, AddEventCommand, AddEventCommandParser and UniquEventList
Created Event Class with the Following Fields:
- Description
- Start Date Time
- End Date Time
- Recurrence (Use of Enums class to only handle for None, Daily, Weekly, Monthly and Yearly)
One Time Events:
Recurrence will be set to None automatically
Recurring Events:
Recurrence will be set according to user input
UniqueEventList:
1. Internal List for Events
- Both Recurring and One TIme Events will be stored in this Internal List 
- Can differentiate through isRecurring method call but thinking of separating the two internal list into their respective types
2. Unmodifiable Internal List for Events
AddEventCommand:
1. Implemented but need to test with the Model 
Changes:
For the magic strings I have made it such …
=> Events For Calendars

src/main/resources/view/result/ResultDisplay.fxml
=> Change command result to wrap text

src/main/java/seedu/address/ui/body/address/PersonDetailCard.java, src/main/java/seedu/address/ui/body/address/PersonDetailPanel.java, src/main/resources/view/body/address/PersonDetailPanel.fxml, src/main/resources/view/body/address/PersonListCard.fxml
* Shows all data fields in Person details
* Remove empty space when there are no tags
* Fix typo in PersonListCard.fxml
* Closes #95 
Before:
After:
=> UI changes on components related to Person

src/main/java/seedu/address/ui/body/address/PersonCard.java, src/main/java/seedu/address/ui/body/address/PersonListDivider.java, src/main/java/seedu/address/ui/body/address/PersonListPanel.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/body/address/PersonListCard.fxml, src/main/resources/view/body/address/PersonListDivider.fxml, src/main/resources/view/body/address/PersonListPanel.fxml
* Closes #99 
* Fixes #100 by optimizing the rendering of `ListCell`s
* Eventually, the logic for splitting the list of Persons should be moved out of the UI
Before:
After:
=> Changes to Person list

src/main/java/seedu/address/ui/body/address/PersonCard.java
=> Fixes duplicated tags issue

src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/fields/Favorite.java, src/main/java/seedu/address/model/person/fields/Gender.java, src/main/java/seedu/address/model/person/fields/Modules.java, src/main/java/seedu/address/model/person/fields/Race.java, src/main/java/seedu/address/model/person/fields/enums/Genders.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/PersonUtil.java, src/test/java/seedu/address/testutil/TypicalPersons.java
=> Changed Person equals logic. Change find command to search if a name contains a word instead of matching perfectly to the name.

src/main/java/seedu/address/ui/body/address/PersonCard.java, src/main/java/seedu/address/ui/body/address/PersonListDivider.java, src/main/java/seedu/address/ui/body/address/PersonListPanel.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/body/address/PersonListCard.fxml
* Closes #112 
* Optimise list rendering
=> Revamp person list rendering

src/main/java/seedu/address/logic/Logic.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/ui/tab/TabType.java, src/main/java/seedu/address/ui/body/BodyPanel.java, src/main/java/seedu/address/ui/body/user/UserPanel.java, src/main/resources/view/body/user/UserPanel.fxml
=> Add tab for user information

src/main/java/seedu/address/logic/commands/AddEventCommand.java, src/main/java/seedu/address/logic/commands/EditUserCommand.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/event/UniqueEventList.java, src/main/java/seedu/address/model/event/fields/Recurrence.java, src/main/java/seedu/address/model/user/User.java, src/main/java/seedu/address/model/user/UserData.java, src/main/java/seedu/address/storage/user/JsonAdaptedEvent.java, src/main/java/seedu/address/storage/user/JsonAdaptedUser.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java
Integrate Events into the User Model and implemented persistent storage as well
* Closes #90 
* Closes #120
=> Integrate Event list into User model and implement persistent storage

src/main/java/seedu/address/commons/core/GuiSettings.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/body/BodyPanel.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/MainWindow.fxml, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java, src/test/java/seedu/address/storage/StorageManagerTest.java
* Closes #126 
* Closes #130 
* Adds toggle under `Menu bar > File > Light/Dark mode`
Dark mode:
Light mode:
=> Light and dark modes!

src/main/java/seedu/address/model/person/fields/Race.java, src/main/java/seedu/address/model/util/SampleDataUtil.java
Fix regex for Race field not allowing the race field to properly load
=> Fix regex for Race field and edit Sampledata util

build.gradle
* Closes #133 
* Pilot run for feature branch workflow
=> Update build.gradle for assertions

src/main/java/seedu/address/logic/commands/AddEventCommand.java, src/main/java/seedu/address/logic/ui/tab/TabType.java, src/main/java/seedu/address/model/event/Event.java, src/main/java/seedu/address/model/event/RecurringEvent.java, src/main/java/seedu/address/model/event/fields/DateTime.java, src/main/java/seedu/address/model/event/fields/Recurrence.java, src/main/java/seedu/address/ui/body/BodyPanel.java, src/main/java/seedu/address/ui/body/calendar/CalendarEventCard.java, src/main/java/seedu/address/ui/body/calendar/CalendarPanel.java, src/main/resources/view/DarkTheme.css, src/test/java/seedu/address/logic/ui/tab/TabUtilTest.java, src/test/java/seedu/address/model/event/fields/DateTimeTest.java
* Checks to ensure `endDateTime` comes after `startDateTime`
* Calculative effective start and end `DateTime`s for recurring events, so that they don't "expire" when their period has elapsed
=> Changes to event DateTime handling

src/main/java/seedu/address/logic/commands/EditContactCommand.java, src/main/java/seedu/address/logic/commands/EditUserCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/logic/parser/editpersoncommandsparser/EditPersonCommandParser.java, src/main/java/seedu/address/logic/parser/editpersoncommandsparser/EditPersonDescriptor.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/fields/Faculty.java, src/main/java/seedu/address/model/user/User.java, src/main/java/seedu/address/storage/addressbook/JsonAdaptedPerson.java, src/main/java/seedu/address/storage/user/JsonAdaptedUser.java, src/main/java/seedu/address/ui/body/address/PersonDetailPanel.java, src/test/java/seedu/address/testutil/PersonBuilder.java
=> add faculty field

src/main/java/seedu/address/model/person/fields/subfields/Tag.java, src/main/java/seedu/address/ui/body/address/PersonCard.java, src/main/java/seedu/address/ui/body/address/PersonDetailPanel.java, src/main/java/seedu/address/ui/body/user/UserPanel.java
* Closes #145 
* Closes #148 
Faculty field:
Fixed tags:
=> Adds faculty field and fixes tags overflow

src/main/java/seedu/address/logic/commands/AddEventCommand.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/event/Event.java, src/main/java/seedu/address/model/event/UniqueEventList.java, src/main/java/seedu/address/model/event/fields/Description.java, src/main/java/seedu/address/model/person/UniquePersonList.java, src/main/java/seedu/address/model/user/User.java, src/main/java/seedu/address/model/user/UserData.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java
The Model class has the following new methods exposed for use. For use for the new Command @nicljr 
I imagined the flow of the command to be:
e.g. command usage: tagpersontoevent 1 Pierce
Check hasPersonWithName("Pierce") -> get person with getPersonWithName("Pierce") -> tag person to event using tagPersonToEvent(index, "Pierce") or untag a person to an event using untagPersonFromEvent(index, "Pierce").
Person getPersonWithName(String name)
- Gets the person object that has the associated name.
boolean hasPersonWithName(String name)
- Checks if a person with that name exists in the addressbook.
- Can be used to assert the existence of Person before calling getPersonWithName in the parser
void tagPersonToEvent(Index index, Person p)
- Tags Event with Person p. The index refers to the index …
=> Add support for users to tag Person to Events.

src/main/java/seedu/address/logic/commands/AddEventCommand.java, src/main/java/seedu/address/logic/commands/TagEventCommand.java, src/main/java/seedu/address/logic/commands/UnTagEventCommand.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/TagEventCommandParser.java, src/main/java/seedu/address/logic/parser/UnTagEventCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/event/UniqueEventList.java, src/main/java/seedu/address/model/user/User.java, src/main/java/seedu/address/model/user/UserData.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java
Changed the Model to have checks the event has already a tagged person or not even if he tags a current person that is already tagged, i pass it out as a success result
Added the Parsers for Tag Event and Untag event Command as well
=> Tag event command and Untag event Command

src/main/java/seedu/address/logic/commands/DeleteEventCommand.java, src/main/java/seedu/address/logic/parser/DeleteEventCommandParser.java
- Added Delete Command Parser
- Added Delete Command
Updated PR
=> Delete event Command

src/main/java/seedu/address/logic/commands/CommandResult.java, src/main/java/seedu/address/logic/commands/DarkModeCommand.java, src/main/java/seedu/address/logic/commands/ExitCommand.java, src/main/java/seedu/address/logic/commands/HelpCommand.java, src/main/java/seedu/address/logic/commands/LightModeCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/enums/LightDarkMode.java, src/test/java/seedu/address/logic/commands/CommandResultTest.java, src/test/java/seedu/address/logic/commands/ExitCommandTest.java, src/test/java/seedu/address/logic/commands/HelpCommandTest.java
=> Add light and dark command.

README.md, build.gradle, docs/AboutUs.md, docs/DevOps.md, docs/SettingUp.md, docs/UserGuide.md, docs/team/Shuggan.md, src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/model/person/fields/enums/Genders.java
Also added @Shuggan's PPP template, think we might have lost it to a merge.
=> Clean up traces of AB-3

docs/UserGuide.md
Included User Guide for add event and delete event
=> User Guide Update

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/AddEventCommand.java, src/main/java/seedu/address/logic/commands/ClearCommand.java, src/main/java/seedu/address/logic/commands/DarkModeCommand.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/DeleteEventCommand.java, src/main/java/seedu/address/logic/commands/EditContactCommand.java, src/main/java/seedu/address/logic/commands/EditUserCommand.java, src/main/java/seedu/address/logic/commands/ExitCommand.java, src/main/java/seedu/address/logic/commands/FavoriteCommand.java, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/commands/HelpCommand.java, src/main/java/seedu/address/logic/commands/LightModeCommand.java, src/main/java/seedu/address/logic/commands/ListCommand.java, src/main/java/seedu/address/logic/commands/SelectCommand.java, src/main/java/seedu/address/logic/commands/TabCommand.java, src/main/java/seedu/address/logic/commands/TagEventCommand.java, src/main/java/seedu/address/logic/commands/UnTagEventCommand.java, src/main/java/seedu/address/logic/commands/UnfavoriteCommand.java, src/main/java/seedu/address/logic/parser/UnTagEventCommandParser.java, src/main/java/seedu/address/ui/HelpWindow.java, src/main/java/seedu/address/ui/result/ResultDisplay.java, src/main/resources/view/result/ResultDisplay.fxml
* `Person -> contact`
* `INPUT -> PARAMETER`
* `SPECIFIER -> PREFIX`
* `Calendar -> Events`
=> Refine help and response messages

docs/UserGuide.md, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/EditEventCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/event/Event.java, src/main/java/seedu/address/model/event/UniqueEventList.java, src/main/java/seedu/address/model/event/fields/DateTime.java, src/main/java/seedu/address/model/person/fields/Tags.java, src/main/java/seedu/address/model/person/fields/subfields/Tag.java, src/main/java/seedu/address/model/user/User.java, src/main/java/seedu/address/model/user/UserData.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java
Patched up some buggy behavior of EditEvent by making events auto-update on command execution.
Closes #194
=> Add auto-updating events to NeoBook.

src/main/java/seedu/address/ui/body/BodyPanel.java, src/main/java/seedu/address/ui/body/address/AddressPanel.java, src/main/java/seedu/address/ui/body/address/PersonDetailPanel.java, src/main/java/seedu/address/ui/body/address/PersonListPanel.java, src/main/java/seedu/address/ui/result/ResultDisplay.java
=> Fix bug where the index shown in the person details pane is wrong

docs/UserGuide.md
* Closes #216 
* Closes #219 
* Closes #222 
* Closes #223 
* Closes #226 
* Closes #238 
* Closes #252 
Regarding validation of input length:
=> Update future plans

src/main/java/seedu/address/logic/commands/CommandResult.java, src/main/java/seedu/address/logic/commands/DarkModeCommand.java, src/main/java/seedu/address/logic/commands/ExitCommand.java, src/main/java/seedu/address/logic/commands/HelpCommand.java, src/main/java/seedu/address/logic/commands/LightModeCommand.java, src/main/java/seedu/address/logic/enums/LightDarkMode.java, src/test/java/seedu/address/logic/commands/CommandResultTest.java, src/test/java/seedu/address/logic/commands/ExitCommandTest.java, src/test/java/seedu/address/logic/commands/HelpCommandTest.java
=> Move LightDarkMode enums into the Logic file and refactored all file paths related to it.

docs/UserGuide.md
improve find ug
add race prefix 
make name optional for find and edit 
closes #227
=> improve find ug, add race prefix and make name optional for find and edit 

docs/DeveloperGuide.md, docs/UserGuide.md
The link seems to be working for me, can somebody double-check that (issue #293)
Edit by @hansstanley 
* Fixes #288 
* Fixes #282 
* Fixes #293
=> Changes to UG/DG

docs/DeveloperGuide.md
* Closes #299 
Based on the following:
=> Add `Planned enhancements` section to DG

docs/team/rachtan27.md, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/test/java/seedu/address/logic/commands/FindCommandTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/PersonUtil.java, src/test/java/seedu/address/testutil/TypicalPersons.java
=> add test cases for find command and update ppp

docs/UserGuide.md
#275 -> I think it was indicated in the Command Format at the start of the UG, i js added one more description
#278 -> I included this at the `important notes to take care of` under the Add event and edit event commands, as inputting 2400 behaviour should be notified to the user
#296 -> I included a To Note section to handle this specific case
=> To-Note #298

docs/UserGuide.md
Fixes all the UG-related issues from issue #312
=> Fix documentation errors

docs/UserGuide.md
Fixes more issues outlined in issue #312 
As well as,
- Adding a UI command summary
- Adding an important requirements section to addevent
- Moving the command format up to the top of the UG under a new section called "How to read the User Guide" rather than under the address-book UG
=> More edits
